const express = require('express')
const router = express.Router()
const boardgame = require('../controllers/boardgame')

router.get('boardgame/:id', boardgame.show)
router.get('boardgame/new', boardgame.new)
router.post('boardgame/new', boardgame.create)
router.get('boardgame/:id/edit', boardgame.edit)
router.put('boardgame/:id', boardgame.update)
router.delete('boardgame/:id', boardgame.delete)
